### ISSUE TITLE
Can't open template files 

### ISSUE THREAD

**Issue by Heechberri** [templateflow/tpl-MNI152NLin2009cAsym#6]
Hi,

I downloaded the zip file, and upon unzipping it, I found that I couldn't open any of the files that are inside the zipped file. I will receive an error message as such.
<img width="644" alt="Screenshot 2019-07-22 at 10 25 56 AM" src="https://user-images.githubusercontent.com/48549033/61602192-314b3000-ac6b-11e9-9c6b-198984bb270b.png">

I wanted to use the brain masked template for group ICA.

Thank you!

Regards,
Vae

**Comment by oesteban** [comment]
> I downloaded the zip file

What zip file?

**Comment by Heechberri** [comment]
Hi,

Sorry I am new to github, I downloaded the zip file as shown. I also tried git clone directly, and I had the same problem

<img width="440" alt="Screenshot 2019-07-22 at 1 57 10 PM" src="https://user-images.githubusercontent.com/48549033/61609439-b133c300-ac88-11e9-90a2-a08d0b1deb8d.png">

Thank you for helping!

**Comment by oesteban** [comment]
Hi @Heechberri,

The issue is that you are not downloading the data at all, you are fetching some internal piece of the repo.

If you want to use TemplateFlow, there are to ways of accessing it:

1. Via [DataLad](https://www.datalad.org/). After you have DataLad installed and working, you can do:

```
datalad install -g ///templateflow/tpl-MNI152NLin2009cAsym
```

2. Using the python client:
```
pip install templateflow
python -c "from templateflow import api; api.get('MNI152NLin2009cAsym')"
```

Both options will end up downloading the data objects you need.

**Comment by Heechberri** [comment]
Hi, 

Oh yes! I got them now! Thank you so much!

**Comment by Oyilin** [comment]
I tried the second method:
Using the python client:
pip install templateflow
python -c "from templateflow import api; api.get('MNI152NLin2009cAsym')"
But I still can't download the files. The error message is shown below.
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='templateflow.s3.amazonaws.com', port=443): Max retries exceeded with url: /tpl-MNI152NLin2009cAsym%5Ctpl-MNI152NLin2009cAsym_res-01_atlas-Schaefer2018_desc-500Parcels17N
etworks_dseg.nii.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000019E66680040>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连 
接尝试失败。'))
